os: linux
dist: xenial
language: php

git:
  depth: 1


before_script:
  - composer install

jobs:
  include:
    - script: composer lint
    - script: composer phpcs
    - script: composer phpstan
    - stage: test & coverage
      install:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      script:
        - composer test
        - php php-coveralls.phar --verbose --config build/coveralls.yml

cache:
  directories:
    - $HOME/.composer/cache