os: linux
dist: xenial
language: php

git:
  depth: 1


before_script:
  - composer install

jobs:
  include:
    - script: composer lint
    - script: composer phpcs

cache:
  directories:
    - $HOME/.composer/cache