os: linux
dist: xenial
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

git:
  depth: 1


before_script:
  - composer install

jobs:
  include:
    - stage: test ParallelLint
      script: composer lint
    - stage: CodeSniffer
      script: composer phpcs
    - stage: PHPStan
      script: composer phpstan
    - stage: Test
      install:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      script:
        - composer test
        - php php-coveralls.phar --verbose --config php/tests/.coveralls.yml
cache:
  directories:
    - $HOME/.composer/cache